library ServiceConstants;
import 'package:flutter/painting.dart';
import 'package:flutter/material.dart';
const dynamic CONTENT_TYPE_JSON = "application/json";
const dynamic CONTENT_TYPE_FORM = "application/x-www-form-urlencoded";
const dynamic ACCEPT_TYPE="application/json";
const dynamic CHARSET="UTF-8";
const dynamic SUCCESS = 200;
const dynamic NETWORK_ERROR = -1;
const dynamic NETWORK_TIMEOUT = -2;
const dynamic NETWORK_JSON_EXCEPTION = -3;
const dynamic NETWORK_NOT_REACHABLE = -4;
const dynamic NON_CONTENT = 201;
const dynamic ACCEPTED = 202;
const dynamic BAD_REQUEST = 400;
const dynamic UNAUTHORIZED = 401;
const dynamic PAYMENT_REQUIRED = 402;
const dynamic FORBIDDEN = 403;
const dynamic NOT_FOUND = 404;
const dynamic METHOD_NOT_ALLOWED = 405;
const dynamic REQUEST_TIMEOUT = 408;
const dynamic REQUEST_ENTITY_TOO_LARGE =413 ;
const dynamic REQUEST_URI_TOO_LONG=414 ;
const dynamic TOO_MANY_REQUESTS =429 ;
const dynamic INTERNAL_SERVER_ERROR =500;
const dynamic BAD_GATEWAY=502 ;
const dynamic SERVICE_UNAVAILABLE =503 ;
const dynamic GATEWAY_TIMEOUT=504 ;
const dynamic CONNECTION_TIMEOUT=5000;
const dynamic RECEIVE_TIMEOUT=5000;
